
/**
 * Represents the lifecycle stages of an interview session.
 * Used for tracking progress and UI state in the Admin and Interview views.
 */
export enum SessionStatus {
  CREATED = 'Created',
  QUESTIONS_READY = 'Questions Ready',
  IN_INTERVIEW = 'In Interview',
  UPLOADING = 'Uploading',
  UPLOADED = 'Uploaded',
  TRANSCRIBING = 'Transcribing',
  ANALYZING = 'Analyzing',
  SCORED = 'Scored',
  REPORT_SENT = 'Report Sent'
}

/**
 * Definition for a single interview question generated by AI.
 */
export interface InterviewQuestion {
  id: string;
  category: 'intro' | 'technical' | 'scenario' | 'behavioral' | 'closing';
  text: string;
}

/**
 * The main data structure for an interview session.
 * Stores configuration, state, and the resulting AI analysis.
 */
export interface InterviewSession {
  id: string;
  otp: string; // 6-digit access code for the candidate
  candidateEmail: string;
  companyName: string;
  jobTitle: string;
  companyWebsite: string;
  jobDescription: string;
  status: SessionStatus;
  questions: InterviewQuestion[];
  transcript?: string; // Full text of the candidate's responses
  report?: InterviewReport; // AI-generated performance analysis
  createdAt: number;
}

/**
 * A scoring dimension (e.g., Technical Knowledge) for the Radar chart.
 */
export interface ScoreDimension {
  label: string;
  score: number; // 0-100 scale
  feedback: string;
}

/**
 * Specific evaluation point for communication skills.
 */
export interface CriterionScore {
  criterion: string;
  score: number; // 1-5 scale
  comment: string;
}

/**
 * The comprehensive analysis produced by the Gemini AI.
 */
export interface InterviewReport {
  overallDimensions: {
    ability: ScoreDimension;
    knowledge: ScoreDimension;
    skillset: ScoreDimension;
    attitude: ScoreDimension;
  };
  technicalCommunication: CriterionScore[];
  strengths: string[];
  improvements: string[];
  summary: string;
}
